### PR TITLE
Create window-x64-debug.yml

### PR DESCRIPTION
**Pull request by 0SameleMetatron0**
Build angle for debug

### CODE REVIEW

**Comment by 0SameleMetatron0** [comment]
...

**Comment by xiaozhuai** [comment]
Merged, will you please also add windows x86 debug target? Thks!

**Comment by xiaozhuai** [comment]
For debug target, you may need pdb files, remove this line `find out/Debug -name "*.pdb" -delete`

**Comment by xiaozhuai** [comment]
And there is a typo in line 31, `is_debug=ture`, `is_debug=true`

**Comment by xiaozhuai** [comment]
Don't worry about it, I will fix it

**Comment by 0SameleMetatron0** [comment]
> Don't worry about it, I will fix it

OK, Thxs. I don't quite understand how to do

**Pull request merged**
